OnlineStore/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using OnlineStore.BusinessLogic.Implementation.Account;
using OnlineStore.BusinessLogic.Implementation.Account.Models;
using OnlineStore.BusinessLogic.Implementation.BrandImplementation;
using OnlineStore.BusinessLogic.Implementation.ColorImplementation;
using OnlineStore.BusinessLogic.Implementation.ComentsImplementation;
using OnlineStore.BusinessLogic.Implementation.Countries;
using OnlineStore.BusinessLogic.Implementation.MeasureImplementation;
using OnlineStore.BusinessLogic.Implementation.Products;
using OnlineStore.BusinessLogic.Implementation.Products.Models;
using OnlineStore.Code;
using OnlineStore.Common.DTOs;
using OnlineStore.Entities.Entities;
using OnlineStore.Entities.Enums;
using OnlineStore.WebApp.Code;
using PagedList;
using System.Security.Claims;

namespace OnlineStore.WebApp.Controllers
{
    public class ProductController : BaseController
    {

        public readonly BrandService BrandService;
        public readonly ColorService ColorService;
        public readonly CategoryService CategoryService;
        public readonly ProductService ProductService;
        public readonly MeasureService MeasureService;
        public readonly CurrentUserDto currentUser;
        public readonly CommentService CommentService;


        public ProductController(ControllerDependencies dependencies, BrandService brandService,
            ColorService colorService, CategoryService categoryService,
            ProductService productService, MeasureService measureService,
            CommentService commentService)
            : base(dependencies)
        {

            BrandService = brandService;
            ColorService = colorService;
            CategoryService = categoryService;
            ProductService = productService;
            MeasureService = measureService;
            currentUser = dependencies.CurrentUser;
            CommentService = commentService;

        }

       
        [HttpGet]
        public IActionResult Create()
        {
            if (currentUser.RoleId == (int)RolesEnum.Admin)
            {
                var model = new ProductCreateModel();
                return View("Create", model);
            }
            return View("Error_NotFound");
        }

        [HttpPost]
        public IActionResult Create(ProductCreateModel model)
        {


            if (model == null)
            {
                return View("Error_NotFound");
            }
            ProductService.CreateProduct(model);
            return RedirectToAction("Index", "Home");

        }

        [HttpGet("/Product/ClothesView/")]
        public IActionResult ClothesView(int genderId, string searchString, int? page, string selectedBrands, int maxPrice, string selectedMeasures)
        {

            if (maxPrice == 0)
            {
                maxPrice = 10000;
            }
            if (page == null || page == 0 )
            {
                page = 1;
            }
            if (!string.IsNullOrEmpty(searchString))
            {
                searchString = searchString.Trim();
            }
            var measuresId = ProductService.TransformStringToInt(selectedMeasures);
            var brandsId = ProductService.TransformStringToInt(selectedBrands);
            double pagesize = 15;
            ViewBag.SelectedMeasures = selectedMeasures;
            ViewBag.MaxPrice = maxPrice;
            ViewBag.Page = page;
            ViewBag.SearchString = searchString;
            ViewBag.PageSize = pagesize;
            ViewBag.GenderId = genderId;
            ViewBag.SelectedBrands = selectedBrands;
            ViewBag.ModelCount = ProductService.GetClothesCount(searchString, genderId, brandsId, maxPrice, measuresId);
            ViewBag.PageCount = Math.Ceiling(ViewBag.ModelCount / pagesize);
            if (ViewBag.PageCount < page && ViewBag.PageCount != 0)
            {
                ViewBag.page = Convert.ToInt32(ViewBag.PageCount);
            }
            else
            {
                ViewBag.page = page;
            }
            var model = ProductService.GetAllClothes(genderId, searchString, ViewBag.page, (int)pagesize, brandsId, maxPrice, measuresId);
            return View(model);
        }

        [HttpGet("/Prduct/ShoesView/")]
        public ViewResult ShoesView(int genderId, string searchString, int? page, string selectedBrands, int maxPrice, string selectedMeasures)
        {
            if (maxPrice == 0)
            {
                maxPrice = 10000;
            }
            if (page == null || page == 0)
            {
                page = 1;
            }
            if (!string.IsNullOrEmpty(searchString))
            {
                searchString = searchString.Trim();
            }
            var price = maxPrice;
            var measuresId = ProductService.TransformStringToInt(selectedMeasures);
            var brandsId = ProductService.TransformStringToInt(selectedBrands);
            double pagesize = 15;

            ViewBag.MaxPrice = maxPrice;
            ViewBag.Page = page;
            ViewBag.SearchString = searchString;
            ViewBag.PageSize = pagesize;
            ViewBag.GenderId = genderId;
            ViewBag.SelectedBrands = selectedBrands;
            ViewBag.SelectedMeasures = selectedMeasures;
            ViewBag.ModelCount = ProductService.GetShoesCount(searchString, genderId, brandsId, price, measuresId);
            ViewBag.PageCount = Math.Ceiling(ViewBag.ModelCount / pagesize);
            if (ViewBag.PageCount < page)
            {
                ViewBag.page = Convert.ToInt32(ViewBag.PageCount);
            }
            else
            {
                ViewBag.page = page;
            }
            var model = ProductService.GetAllShoes(genderId, searchString, ViewBag.page, (int)pagesize, brandsId, price, measuresId);
            
            return View(model);
        }

        [HttpGet("/ProductByCategory/")]
        public IActionResult CategoryView(int categoryId, string searchString, int? page, string selectedBrands, int maxPrice, string selectedMeasures)
        {

            if (maxPrice == 0)
            {
                maxPrice = 10000;
            }
            if (!string.IsNullOrEmpty(searchString))
            {
                searchString = searchString.Trim();
            }
            double pagesize = 15;
            var measuresId = ProductService.TransformStringToInt(selectedMeasures);
            var brandsId = ProductService.TransformStringToInt(selectedBrands);
            if (page == null || page == 0)
            {
                page = 1;
            }
            ViewBag.SelectedMeasures = selectedMeasures;
            ViewBag.MaxPrice = maxPrice;
            ViewBag.Page = page;
            ViewBag.SearchString = searchString;
            ViewBag.PageSize = pagesize;
            ViewBag.SelectedBrands = selectedBrands;
            ViewBag.CategoryId = categoryId;
            ViewBag.ModelCount = ProductService.GetCategoryCount(searchString, categoryId, brandsId, maxPrice, measuresId);
            ViewBag.PageCount = Math.Ceiling(ViewBag.ModelCount / pagesize);
            ViewBag.TypeId = ProductService.GetTypeId(categoryId);
            if (ViewBag.PageCount < page)
            {
                ViewBag.page = Convert.ToInt32(ViewBag.PageCount);
            }
            else
            {
                ViewBag.page = page;
            }
            var model = ProductService.GetProuctsByCategory(categoryId, searchString, ViewBag.page, (int)pagesize, brandsId, maxPrice, measuresId);
           
            return View(model);
        }


        [HttpGet("/Product/GenderView/")]
        public IActionResult GenderView(int genderId, string searchString, int? page, string selectedBrands, int maxPrice, string selectedMeasures)
        { 
            if (maxPrice == 0)
            {
                maxPrice = 10000;
            }
            if (page == null || page == 0)
            {
                page = 1;
            }
            if (!string.IsNullOrEmpty(searchString))
            {
                searchString = searchString.Trim();
            }
            var measuresId = ProductService.TransformStringToInt(selectedMeasures);
            var brandsId = ProductService.TransformStringToInt(selectedBrands);
            double pagesize = 15;
            ViewBag.SelectedMeasures = selectedMeasures;
            ViewBag.MaxPrice = maxPrice;
            ViewBag.Page = page;
            ViewBag.SearchString = searchString;
            ViewBag.PageSize = pagesize;
            ViewBag.GenderId = genderId;
            ViewBag.SelectedBrands = selectedBrands;
            ViewBag.ModelCount = ProductService.GetGenderCount(searchString, genderId, brandsId, maxPrice, measuresId);
            ViewBag.PageCount = Math.Ceiling(ViewBag.ModelCount / pagesize);
            if (ViewBag.PageCount < page)
            {
                ViewBag.page = Convert.ToInt32(ViewBag.PageCount);
            }
            else
            {
                ViewBag.page = page;
            }
            var model = ProductService.GetProuctsByGender(genderId, searchString, ViewBag.page, (int)pagesize, brandsId, maxPrice, measuresId);
             
            return View(model);
        }

        [HttpGet]
        public IActionResult ProductDetails(Guid id)
        {
            try
            {
                var model = ProductService.GetProductById(id);
                return View("ProductDetails", model);
            }
            catch (System.Exception)
            {
                return View("Error_NotFound");
            }
        }

        [HttpGet]
        public IActionResult AddProductMeasure(Guid id)
        {
            if (currentUser.RoleId != (int)RolesEnum.Admin)
            {
                return View("Error_NotFound");
            }

            var model = new MeasureQuantityModel();

OnlineStore/Controllers/UserAccountController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using OnlineStore.BusinessLogic.Implementation.Account;
using OnlineStore.BusinessLogic.Implementation.Account.Models;
using OnlineStore.BusinessLogic.Implementation.Countries;
using OnlineStore.Code;
using OnlineStore.Common.DTOs;
using OnlineStore.WebApp.Code;
using System.Security.Claims;
using PagedList;
using OnlineStore.Entities.Enums;
using Microsoft.AspNetCore.Authorization;

namespace OnlineStore.WebApp.Controllers
{
    public class UserAccountController : BaseController
    {
        private readonly UserAccountService UserAccountService;
        private readonly CountriesService CountriesService;
        private readonly IEmailSender EmailSender;

        public UserAccountController(ControllerDependencies dependencies, UserAccountService userAccountService, CountriesService countriesService, IEmailSender emailSender)
            : base(dependencies)
        {
            UserAccountService = userAccountService;
            CountriesService = countriesService;
            EmailSender = emailSender;
        }


        public ViewResult AllUsers(string searchString, int? page)
        {
            double pagesize = 15;
            ViewBag.ModelCount = UserAccountService.GetUserCount(searchString);
            ViewBag.PageCount = Math.Ceiling(ViewBag.ModelCount / pagesize);
            if (ViewBag.PageCount < page)
            {
                ViewBag.page = Convert.ToInt32(ViewBag.PageCount);
            }
            else
            {
                ViewBag.page = page;
            }

            if (ViewBag.page == null)
            {
                ViewBag.page = 1;

            }
            ViewBag.SearchString = searchString;
            ViewBag.PageSize = pagesize;

            if (CurrentUser.RoleId != (int)RolesEnum.Admin)
            {
                return View("Error_NotFound");
            }

            var model = UserAccountService.GetAllUsers(searchString, (int)pagesize, ViewBag.page);

            return View(model);
        }


        [HttpGet]
        public IActionResult Register()
        {
            var model = new RegisterModel();
            return View("Register", model);
        }

        [HttpPost]
        public async Task<IActionResult> RegisterAsync(RegisterModel model)
        {
            if (model == null)
            {
                return View("Error_NotFound");
            }

            UserAccountService.RegisterNewUser(model);

            LoginModel loginModel = new LoginModel();
            loginModel.Email = model.Email;
            loginModel.Password = model.Password;
            _ = Login(loginModel);
            var receiver = model.Email;
            var subject = "Welcome to our store";
            var message = "Welcome to our store";
            await EmailSender.SendEmailAsync(receiver, subject, message);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult Login()
        {
            var model = new LoginModel();
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginModel model)
        {
            var user = UserAccountService.Login(model.Email, model.Password);

            if (!user.IsAuthenticated)
            {
                model.AreCredentialsInvalid = true;
                return View(model);
            }

            await LogIn(user);


            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await LogOut();

            return RedirectToAction("Index", "Home");
        }

        private async Task LogIn(CurrentUserDto user)
        {
            var claims = new List<Claim>
            {
                new Claim("Id", user.Id.ToString()),
                new Claim(ClaimTypes.Name, $"{user.FirstName} {user.LastName}"),
                new Claim(ClaimTypes.Email, user.Email),
                new Claim("RoleId", user.RoleId.ToString()),
                new Claim("IsAdmin", user.IsAdmin.ToString()),

            };

            var identity = new ClaimsIdentity(claims, "Cookies");
            var principal = new ClaimsPrincipal(identity);

           

            await HttpContext.SignInAsync(
                    scheme: "OnlineStoreCookies",
                    principal: principal);
        }

        [HttpGet]
        public IActionResult Profile()
        {
            var Id = new Guid(CurrentUser.Id);
            var model = UserAccountService.GetUserProfile(Id);
            return View(model);
        }

        [HttpGet]
        public IActionResult EditProfile()
        {
            var Id = new Guid(CurrentUser.Id);
            var model = UserAccountService.GetUserProfile(Id);
            ViewBag.CountryId = model.CountryId;
            return View(model);
        }

        [HttpPost]
        public IActionResult EditProfile(ProfileModel model)
        {

            UserAccountService.UpdateUserProfile(model);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult ShoppingCart()
        {

            var model = UserAccountService.GetUserShoppingCart();
            return View(model);
        }

        [HttpGet]
        public IActionResult WishList()
        {

            var model = UserAccountService.GetUserWishList();
            return View(model);
        }

        public IActionResult DeleteByAdmin(Guid UserId)
        {
            if (CurrentUser.RoleId != (int)RolesEnum.Admin)
            {
                return View("Error_NotFound");
            }

            UserAccountService.DeleteUser(UserId);
            return Ok();
        }


        public IActionResult DeleteAccount()
        {

            UserAccountService.DeleteAccount();
            _ = Logout();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult MakeAdmin(Guid UserId)
        {
            if (CurrentUser.RoleId != (int)RolesEnum.Admin)
            {
                return View("Error_NotFound");

            }
            UserAccountService.MakeAdmin(UserId);
            return Ok();
        }
        public IActionResult MakeUser(Guid UserId)
        {
            if (CurrentUser.RoleId != (int)RolesEnum.Admin)
            {
                return View("Error_NotFound");

            }
            UserAccountService.MakeUser(UserId);
            return Ok();
        }

        private async Task LogOut()
        {
            await HttpContext.SignOutAsync(scheme: "OnlineStoreCookies");
        }


        [HttpGet]
        public IActionResult Orders()
        {

            var model = UserAccountService.GetUserOrders();
            return View(model);
        }

        [HttpGet]

        public IActionResult Top10Users()
        {
            if (CurrentUser.RoleId != (int)RolesEnum.Admin)
            {
                return View("Error_NotFound");

            }
            var model = UserAccountService.GetTopUsers();
            return View(model);
        }



        [HttpGet]
        public IActionResult Medals()
        {
            if (CurrentUser.RoleId != (int)RolesEnum.Admin)
            {
                return View("Error_NotFound");

            }
            return View();
        }
    }
}

OnlineStore/Views/Shared/Error_InternalServerError.cshtml
@model ErrorViewModel
@{
    ViewData["Title"] = "Error";
}

<h1 class="text-danger">Error 500</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>

OnlineStore/Views/Shared/Error_NotFound.cshtml
@model ErrorViewModel
@{
    ViewData["Title"] = "Error";
}

<h1 class="text-danger">Error 404</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>

OnlineStore/Views/Shared/Error_Unauthorized.cshtml
@model ErrorViewModel
@{
    ViewData["Title"] = "Error";
}

<h1 class="text-danger">Error 301</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>

OnlineStore/Views/Shared/_Layout.cshtml
@inject OnlineStore.Common.DTOs.CurrentUserDto CurrentUser
@{

    ViewBag.Title = "ProductsView";

}
<style>
    .footer {
        position: absolute;
        bottom: 0;
        width: 100%;
        background-color: #f9f9f9;
        padding: 5px 0;
        box-shadow: 0px -2px 5px rgba(0, 0, 0, 0.1);
    }
</style>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/Layout/Layout.css" />
    @*<link rel="stylesheet" href="~/OnlineStore.styles.css" asp-append-version="true" />*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-darkt bg-dark border-bottom box-shadow mb-3" id="menu">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color: white"><i class="bi bi-house">Home </i></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" id="main_nav">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item active ">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <div class="collapse navbar-collapse" id="main_nav">
                            <ul class="navbar-nav">
                                <li class="nav-item dropdown" id="myDropdown">
                                    <a class="nav-link dropdown-toggle text-white" href="#" data-bs-toggle="dropdown">  Products  </a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a class="dropdown-item" href="@Url.Action("GenderView", "Product", new { genderId = 1 })"> Men &equiv; </a>
                                            <ul class="submenu dropdown-menu">
                                                <li>
                                                    <a class="dropdown-item" href="@Url.Action("ShoesView", "Product", new { genderId = 1 })">Shoes &equiv; </a>
                                                    <ul class="submenu dropdown-menu">
                                                        <li><a class="dropdown-item" href="@Url.Action("CategoryView", "Product", new { categoryId = 1 })">Sneakers</a></li>
                                                        <li><a class="dropdown-item" href="@Url.Action("CategoryView", "Product", new { categoryId = 2 })">Low Top</a></li>
                                                        <li><a class="dropdown-item" href="@Url.Action("CategoryView", "Product", new { categoryId = 3 })">Slides</a></li>
                                                        <li><a class="dropdown-item" href="@Url.Action("CategoryView", "Product", new { categoryId = 4 })">High Tops</a></li>
                                                        <li><a class="dropdown-item" href="@Url.Action("CategoryView", "Product", new { categoryId = 5 })">Boots </a></li>
                                                    </ul>
                                                </li>
                                                <li>
                                                    <a class="dropdown-item" href="@Url.Action("ClothesView", "Product", new { genderId = 1 })">Clothes &equiv; </a>
                                                    <ul class="submenu dropdown-menu">
                                                        <li><a class="dropdown-item" href="@Url.Action("CategoryView", "Product", new { categoryId = 11 })">T-Shirts</a></li>
                                                        <li><a class="dropdown-item" href="@Url.Action("CategoryView", "Product", new { categoryId = 12 })">Shirts</a></li>
                                                        <li><a class="dropdown-item" href="@Url.Action("CategoryView", "Product", new { categoryId = 13 })">Shorts</a></li>
                                                        <li><a class="dropdown-item" href="@Url.Action("CategoryView", "Product", new { categoryId = 14 })">Trousers</a></li>
                                                        <li><a class="dropdown-item" href="@Url.Action("CategoryView", "Product", new { categoryId = 15 })">Hoodies and Sweaters</a></li>
                                                        <li><a class="dropdown-item" href="@Url.Action("CategoryView", "Product", new { categoryId = 16 })">UnderWear</a></li>
                                                        <li><a class="dropdown-item" href="@Url.Action("CategoryView", "Product", new { categoryId = 17 })">Jackets and Coats</a></li>
                                                    </ul>
                                                </li>
                                            </ul>
                                        </li>


                                        <li>
                                            <a class="dropdown-item" href="@Url.Action("GenderView", "Product", new { genderId = 2 })"> Women &equiv; </a>
                                            <ul class="submenu dropdown-menu">
                                                <li>
                                                    <a class="dropdown-item" href="@Url.Action("ShoesView", "Product", new { genderId = 2 })">Shoes &equiv; </a>
                                                    <ul class="submenu dropdown-menu">
                                                        <li><a class="dropdown-item" href="@Url.Action("CategoryView", "Product", new { categoryId = 6 })">Sneakers</a></li>
                                                        <li><a class="dropdown-item" href="@Url.Action("CategoryView", "Product", new { categoryId = 7 })">Low Top</a></li>
                                                        <li><a class="dropdown-item" href="@Url.Action("CategoryView", "Product", new { categoryId = 8 })">Slides</a></li>
                                                        <li><a class="dropdown-item" href="@Url.Action("CategoryView", "Product", new { categoryIdid = 9 })">High Tops</a></li>
                                                        <li><a class="dropdown-item" href="@Url.Action("CategoryView", "Product", new { categoryId = 10 })">Boots</a></li>
                                                    </ul>
                                                </li>
                                                <li>
                                                    <a class="dropdown-item" href="@Url.Action("ClothesView", "Product", new { genderId = 2 })">Clothes &equiv; </a>
                                                    <ul class="submenu dropdown-menu">
                                                        <li><a class="dropdown-item" href="@Url.Action("CategoryView", "Product", new { categoryId = 18 })">T-Shirts</a></li>
                                                        <li><a class="dropdown-item" href="@Url.Action("CategoryView", "Product", new { categoryId = 19 })">Shirts</a></li>
                                                        <li><a class="dropdown-item" href="@Url.Action("CategoryView", "Product", new { categoryId = 20 })">Shorts</a></li>
                                                        <li><a class="dropdown-item" href="@Url.Action("CategoryView", "Product", new { categoryId = 21 })">Trousers</a></li>
                                                        <li><a class="dropdown-item" href="@Url.Action("CategoryView", "Product", new { categoryId = 22 })">Hoodies and Sweaters</a></li>
                                                        <li><a class="dropdown-item" href="@Url.Action("CategoryView", "Product", new { categoryId = 23 })">UnderWear</a></li>
                                                        <li><a class="dropdown-item" href="@Url.Action("CategoryView", "Product", new { categoryId = 24 })">Dress</a></li>
                                                        <li><a class="dropdown-item" href="@Url.Action("CategoryView", "Product", new { categoryId = 25 })">Skirts</a></li>
                                                        <li><a class="dropdown-item" href="@Url.Action("CategoryView", "Product", new { categoryId = 26 })">Jackets and Coats</a></li>
                                                    </ul>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>

                        @if (CurrentUser.IsAuthenticated)
                        {
                            @if (CurrentUser.RoleId == 1)
                            {
                                <ul class="navbar-nav">
                                    <li class="nav-item dropdown" id="myDropdown">
                                        <a class="nav-link dropdown-toggle text-white" href="#" data-bs-toggle="dropdown">  Admin Actions  </a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a class="dropdown-item" href="@Url.Action("Create", "Product", new { id = 1 })">Create Product</a>
                                            </li>
                                            <li>
                                                <a class="dropdown-item" href="@Url.Action("AllUsers", "UserAccount" , new {page = 1})">Users</a>
                                            </li>
                                            <li>
                                                <a class="dropdown-item" href="@Url.Action("Top10Users", "UserAccount")">Top Users</a>
                                            </li>
                                            <li>
                                                <a class="dropdown-item" href="@Url.Action("Top10Products", "Product")">Top Products</a>
                                            </li>
                                            <li>
                                                <a class="dropdown-item" href="@Url.Action("Medals", "UserAccount")">Medals</a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            }
                        }
                    </ul>

                </div>
                <div>

                    @if (CurrentUser.IsAuthenticated)
                    {
                        <a href="@Url.Action("Profile", "UserAccount", new { id = CurrentUser.Id })" class="text-decoration-none text-white"><i class="bi bi-person-circle"></i></a>
                        <a asp-controller="UserAccount" asp-action="ShoppingCart" style="color: white ;text-decoration :none "> <i class="bi bi-cart-fill"></i></a>
                        <a asp-controller="UserAccount" asp-action="WishList" style="color: white"><i class="bi bi-heart-fill"></i></a>

                        <a href="#" onclick="confirmLogout()" style="color: white"><i class="bi bi-box-arrow-right"></i>Log out</a>


                    }
                    else
                    {
                        <a asp-controller="UserAccount" asp-action="Login" style="color: white; margin-right: 10px; text-decoration: none"><i class="bi bi-box-arrow-in-right"></i> Log in </a>
                        <a asp-controller="UserAccount" asp-action="Register" style="color: white; text-decoration: none">Register</a>

                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">

        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>




    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<script>
    function confirmLogout() {
        // Folosiți funcția `confirm()` pentru a afișa o casetă de dialog de confirmare
        var result = confirm("Are you sure you want to log out?");

        // Verificați răspunsul utilizatorului
        if (result) {
            // Dacă utilizatorul a confirmat, continuați să îi deconectați
            window.location.href = '/UserAccount/Logout'; // sau utilizați metoda corespunzătoare pentru logout
        }
    }

</script>