OnlineStore/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Controllers;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using OnlineStore.BusinessLogic.Implementation.EmailImplementation;
using OnlineStore.BusinessLogic.Implementation.OrderImplementation;
using OnlineStore.Code;
using OnlineStore.WebApp.Code;
using System.Net.Mail;
using System.Web.Mvc;
using IronPdf;

namespace OnlineStore.WebApp.Controllers
{
    public class OrderController : BaseController
    {
        private readonly OrderService orderService;
        private readonly EmailService emailService;

        public OrderController(ControllerDependencies dependencies, OrderService orderService, EmailService emailService) : base(dependencies)
        {
            this.orderService = orderService;
            this.emailService = emailService;
        }

        public IActionResult OrderDetails(int Id)
        {
            var model = orderService.GetAllOrder(Id);
            return View(model);
        }


    }
}

OnlineStore/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineStore.BusinessLogic.Implementation.Account;
using OnlineStore.BusinessLogic.Implementation.NewFolder;
using OnlineStore.Code;
using OnlineStore.Common.DTOs;
using OnlineStore.DataAccess;
using OnlineStore.Entities.Entities;
using OnlineStore.WebApp.Code;
using Stripe.Checkout;
using iTextSharp.text;
using iTextSharp.text.pdf;
using OnlineStore.BusinessLogic.Implementation.EmailImplementation;
using MimeKit;
using MimeKit.Text;
using MimeKit.IO;
using MailKit.Net.Smtp;
using System;
using Microsoft.AspNetCore.Mvc;
using OnlineStore.BusinessLogic.Implementation.Products;

namespace OnlineStore.WebApp.Controllers
{
    public class ShoppingCartController : BaseController
    {
        public readonly ShoppingCartService ShoppingCartService;
        public new readonly CurrentUserDto CurrentUser;
        public readonly UserAccountService UserAccountService;
        public readonly EmailService EmailService;
        public readonly ProductService ProductService;
        public ShoppingCartController(ControllerDependencies dependencies, ShoppingCartService shoppingCartService, UserAccountService userAccountService, EmailService emailService, ProductService productService) : base(dependencies)
        {
            ShoppingCartService = shoppingCartService;
            CurrentUser = dependencies.CurrentUser;
            UserAccountService = userAccountService;
            EmailService = emailService;
            ProductService = productService;
        }

        [HttpPost]
        public IActionResult RemoveItem(Guid productId, string measure)
        {

            ShoppingCartService.RemoveItem(productId, measure);
            return Ok();
        }

        [HttpPost]
        public IActionResult IncreaseQuantity(Guid productId, string measure)
        {
            try
            {
                ShoppingCartService.IncreaseQuantity(productId, measure);
                return Ok();
            }
            catch (System.Exception)
            {
                return View("Error_NoutFound");
            }

        }

        [HttpPost]
        public IActionResult DecreaseQuantity(Guid productId, string measure)
        {
            try
            {
                ShoppingCartService.DecreaseQuantity(productId, measure);
                return Ok();
            }
            catch (System.Exception)
            {
                return View("Error_NoutFound");
            }
        }

        public IActionResult OrderConfirmation()
        {
            var cart = UserAccountService.GetUserShoppingCart();
            var receipt = new Receipt();
            Guid Id = new Guid(CurrentUser.Id);
            receipt.TotalPrice = ShoppingCartService.GetTotalPrice();
            receipt.UserId = Id;
            ShoppingCartService.AddReceipt(receipt);
            Document document = new Document(PageSize.A4, 50, 50, 50, 50); 
            string path = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
            PdfWriter.GetInstance(document, new FileStream(path + "/Receipt.pdf", FileMode.Create));
            document.Open();

           
            var titleFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 14, BaseColor.BLACK);
            var headingFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 10, BaseColor.BLACK);
            var normalFont = FontFactory.GetFont(FontFactory.HELVETICA, 10, BaseColor.BLACK);

            
            var table = new PdfPTable(4);
            table.WidthPercentage = 100;

            
            var titleCell = new PdfPCell(new Phrase("Your Order Receipt", titleFont));
            titleCell.Colspan = 4;
            titleCell.HorizontalAlignment = Element.ALIGN_CENTER;
            titleCell.Border = 0; 
            table.AddCell(titleCell);

           
            var headers = new string[] { "Product", "Size", "Price", "Quantity" };
            foreach (var header in headers)
            {
                var headerCell = new PdfPCell(new Phrase(header, headingFont));
                headerCell.HorizontalAlignment = Element.ALIGN_CENTER;
                headerCell.BackgroundColor = BaseColor.LIGHT_GRAY;
                table.AddCell(headerCell);
            }

            foreach (var item in cart)
            {
                var product = ProductService.GetProductById(item.ProductId);

               
                table.AddCell(new PdfPCell(new Phrase(product.Name, normalFont)));
                table.AddCell(new PdfPCell(new Phrase(item.ProductSize, normalFont)));
                table.AddCell(new PdfPCell(new Phrase("$" + (product.Price - product.Price * product.Discount / 100) * item.Quantity, normalFont)));
                table.AddCell(new PdfPCell(new Phrase(item.Quantity.ToString(), normalFont)));

                var OrderedItem = new OrderedItems();
                OrderedItem.ProductId = item.ProductId;
                OrderedItem.OrderId = receipt.Id;
                OrderedItem.Quantity = item.Quantity;

                ShoppingCartService.AddOrderedItem(OrderedItem, receipt.Id);
                ShoppingCartService.RemoveItem(item.ProductId, item.ProductSize);
                ShoppingCartService.RemoveFromDataBase(item.ProductId, item.ProductSize, item.Quantity);
            }

           
            var totalCell = new PdfPCell(new Phrase("Total Price: $" + receipt.TotalPrice, headingFont));
            totalCell.Colspan = 4;
            totalCell.HorizontalAlignment = Element.ALIGN_RIGHT;
            totalCell.Border = 0;
            table.AddCell(totalCell);

            
            document.Add(table);

            document.Close();
            _ = EmailService.SendDocument(CurrentUser.Email, "Order Receipt", "Thank you for your order", path + "/Receipt.pdf");
            return View("OrderConfirmation", cart);
        }


        //public IActionResult CheckOut()
        //{

        //    var domain = "https://localhost:7108/";
        //    var options = new SessionCreateOptions
        //    {
        //        SuccessUrl = domain + $"ShoppingCart/OrderConfirmation",
        //        CancelUrl = domain + $"UserAccount/ShoppingCart",
        //        LineItems = new List<SessionLineItemOptions>(),
        //        Mode = "payment",

        //    };

        //    var cart = UserAccountService.GetUserShoppingCart();
        //    foreach (var item in cart)
        //    {
        //        var sessionListItem = new SessionLineItemOptions
        //        {
        //            PriceData = new SessionLineItemPriceDataOptions
        //            {

        //                UnitAmount = (long?)(item.ProductPrice - item.ProductPrice * item.ProductDiscount / 100) * 100,
        //                Currency = "usd",
        //                ProductData = new SessionLineItemPriceDataProductDataOptions
        //                {
        //                    Name = $"{item.ProductName}  {item.ProductSize}"

        //                },
        //            },
        //            Quantity = item.Quantity,
        //        };

        //        options.LineItems.Add(sessionListItem);
        //    }
        //    var service = new SessionService();
        //    Session session = service.Create(options);

        //    Response.Headers.Add("Location", session.Url);
        //    return new StatusCodeResult(303);
        //}
        public IActionResult CheckOut()
        {
            var domain = "https://localhost:7108/";
            var options = new SessionCreateOptions
            {
                SuccessUrl = domain + $"ShoppingCart/OrderConfirmation",
                CancelUrl = domain + $"UserAccount/ShoppingCart",
                LineItems = new List<SessionLineItemOptions>(),
                Mode = "payment",
                ShippingAddressCollection = new SessionShippingAddressCollectionOptions
                {
                    AllowedCountries = new List<string>
            {
                "US", "CA","RO" // Add other allowed countries as needed
            }
                }
            };

            var cart = UserAccountService.GetUserShoppingCart();
            foreach (var item in cart)
            {
                var sessionListItem = new SessionLineItemOptions
                {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                        UnitAmount = (long?)(item.ProductPrice - item.ProductPrice * item.ProductDiscount / 100) * 100,
                        Currency = "usd",
                        ProductData = new SessionLineItemPriceDataProductDataOptions
                        {
                            Name = $"{item.ProductName}  {item.ProductSize}"
                        }
                    },
                    Quantity = item.Quantity
                };

                options.LineItems.Add(sessionListItem);
            }

            var service = new SessionService();
            Session session = service.Create(options);

            Response.Headers.Add("Location", session.Url);
            return new StatusCodeResult(303);
        }

    }
}

OnlineStore/Controllers/UserAccountController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using OnlineStore.BusinessLogic.Implementation.Account;
using OnlineStore.BusinessLogic.Implementation.Account.Models;
using OnlineStore.BusinessLogic.Implementation.Countries;
using OnlineStore.Code;
using OnlineStore.Common.DTOs;
using OnlineStore.WebApp.Code;
using System.Security.Claims;
using PagedList;
using OnlineStore.Entities.Enums;
using Microsoft.AspNetCore.Authorization;

namespace OnlineStore.WebApp.Controllers
{
    public class UserAccountController : BaseController
    {
        private readonly UserAccountService UserAccountService;
        private readonly CountriesService CountriesService;
        private readonly IEmailSender EmailSender;

        public UserAccountController(ControllerDependencies dependencies, UserAccountService userAccountService, CountriesService countriesService, IEmailSender emailSender)
            : base(dependencies)
        {
            UserAccountService = userAccountService;
            CountriesService = countriesService;
            EmailSender = emailSender;
        }


        public ViewResult AllUsers(string searchString, int? page)
        {
            double pagesize = 15;
            ViewBag.ModelCount = UserAccountService.GetUserCount(searchString);
            ViewBag.PageCount = Math.Ceiling(ViewBag.ModelCount / pagesize);
            if (ViewBag.PageCount < page)
            {
                ViewBag.page = Convert.ToInt32(ViewBag.PageCount);
            }
            else
            {
                ViewBag.page = page;
            }

            if (ViewBag.page == null)
            {
                ViewBag.page = 1;

            }
            ViewBag.SearchString = searchString;
            ViewBag.PageSize = pagesize;

            if (CurrentUser.RoleId != (int)RolesEnum.Admin)
            {
                return View("Error_NotFound");
            }

            var model = UserAccountService.GetAllUsers(searchString, (int)pagesize, ViewBag.page);

            return View(model);
        }


        [HttpGet]
        public IActionResult Register()
        {
            var model = new RegisterModel();
            return View("Register", model);
        }

        [HttpPost]
        public async Task<IActionResult> RegisterAsync(RegisterModel model)
        {
            if (model == null)
            {
                return View("Error_NotFound");
            }

            UserAccountService.RegisterNewUser(model);

            LoginModel loginModel = new LoginModel();
            loginModel.Email = model.Email;
            loginModel.Password = model.Password;
            _ = Login(loginModel);
            var receiver = model.Email;
            var subject = "Welcome to our store";
            var message = "Welcome to our store";
            await EmailSender.SendEmailAsync(receiver, subject, message);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult Login()
        {
            var model = new LoginModel();
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginModel model)
        {
            var user = UserAccountService.Login(model.Email, model.Password);

            if (!user.IsAuthenticated)
            {
                model.AreCredentialsInvalid = true;
                return View(model);
            }

            await LogIn(user);


            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await LogOut();

            return RedirectToAction("Index", "Home");
        }

        private async Task LogIn(CurrentUserDto user)
        {
            var claims = new List<Claim>
            {
                new Claim("Id", user.Id.ToString()),
                new Claim(ClaimTypes.Name, $"{user.FirstName} {user.LastName}"),
                new Claim(ClaimTypes.Email, user.Email),
                new Claim("RoleId", user.RoleId.ToString()),
                new Claim("IsAdmin", user.IsAdmin.ToString()),

            };

            var identity = new ClaimsIdentity(claims, "Cookies");
            var principal = new ClaimsPrincipal(identity);

           

            await HttpContext.SignInAsync(
                    scheme: "OnlineStoreCookies",
                    principal: principal);
        }

        [HttpGet]
        public IActionResult Profile()
        {
            var Id = new Guid(CurrentUser.Id);
            var model = UserAccountService.GetUserProfile(Id);
            return View(model);
        }

        [HttpGet]
        public IActionResult EditProfile()
        {
            var Id = new Guid(CurrentUser.Id);
            var model = UserAccountService.GetUserProfile(Id);
            ViewBag.CountryId = model.CountryId;
            return View(model);
        }

        [HttpPost]
        public IActionResult EditProfile(ProfileModel model)
        {

            UserAccountService.UpdateUserProfile(model);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult ShoppingCart()
        {

            var model = UserAccountService.GetUserShoppingCart();
            return View(model);
        }

        [HttpGet]
        public IActionResult WishList()
        {

            var model = UserAccountService.GetUserWishList();
            return View(model);
        }

        public IActionResult DeleteByAdmin(Guid UserId)
        {
            if (CurrentUser.RoleId != (int)RolesEnum.Admin)
            {
                return View("Error_NotFound");
            }

            UserAccountService.DeleteUser(UserId);
            return Ok();
        }


        public IActionResult DeleteAccount()
        {

            UserAccountService.DeleteAccount();
            _ = Logout();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult MakeAdmin(Guid UserId)
        {
            if (CurrentUser.RoleId != (int)RolesEnum.Admin)
            {
                return View("Error_NotFound");

            }
            UserAccountService.MakeAdmin(UserId);
            return Ok();
        }
        public IActionResult MakeUser(Guid UserId)
        {
            if (CurrentUser.RoleId != (int)RolesEnum.Admin)
            {
                return View("Error_NotFound");

            }
            UserAccountService.MakeUser(UserId);
            return Ok();
        }

        private async Task LogOut()
        {
            await HttpContext.SignOutAsync(scheme: "OnlineStoreCookies");
        }


        [HttpGet]
        public IActionResult Orders()
        {

            var model = UserAccountService.GetUserOrders();
            return View(model);
        }

        [HttpGet]

        public IActionResult Top10Users()
        {
            if (CurrentUser.RoleId != (int)RolesEnum.Admin)
            {
                return View("Error_NotFound");

            }
            var model = UserAccountService.GetTopUsers();
            return View(model);
        }



        [HttpGet]
        public IActionResult Medals()
        {
            if (CurrentUser.RoleId != (int)RolesEnum.Admin)
            {
                return View("Error_NotFound");

            }
            return View();
        }
    }
}

OnlineStore/Views/UserAccount/AllUsers.cshtml
@model IEnumerable<OnlineStore.Common.DTOs.UserDto>
@inject OnlineStore.Common.DTOs.CurrentUserDto CurrentUser
@{
    ViewBag.Title = "Users";
    ViewBag.PageCount = Convert.ToInt32(ViewBag.Pagecount);
    ViewBag.Page = Convert.ToInt32(ViewBag.Page);
    ViewBag.PageSize = Convert.ToInt32(ViewBag.PageSize);
    ViewBag.ModelCount = Convert.ToInt32(ViewBag.ModelCount);
    ViewBag.SerchString = ViewBag.SerchString;

}

<h1>Users</h1>

@using (Html.BeginForm("AllUsers", "UserAccount", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString",ViewBag.SerchString as string)
        <input type="submit" value="Search" />
    </p>
}

<div>
    <table class="table" id="user_pagination">
        <thead>
            <tr>
                <th>User ID</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>User Name</th>
                <th>Role</th>

            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model)
            {
                <tr id="item-@item.UserId">
                    <td>@item.UserId</td>
                    <td>@item.FirstName</td>
                    <td>@item.LastName</td>
                    <td>@item.Email</td>
                    <td>@item.UserName</td>
                    <td>@item.Role</td>
                    <td>
                        @if (CurrentUser.Id != item.UserId.ToString())
                        {
                            <button class="btn btn-danger" onclick="RemoveUser('@item.UserId')">Remove</button>
                        }
                        @if (CurrentUser.Id != item.UserId.ToString() && item.Role != "Admin")
                        {
                            <button class="btn btn-primary" onclick="MakeAdmin('@item.UserId')">Make Admin</button>
                        }
                        @if (CurrentUser.Id != item.UserId.ToString() && item.Role != "User")
                        {
                            <button class="btn btn-primary" onclick="MakeUser('@item.UserId')">Make User</button>
                        }
                    </td>
                </tr>
            }
    </table>

</div>


<nav aria-label="...">
    <ul class="pagination">

        @if (ViewBag.Page != 1)
        {
            <li class="page-item">
                <a class="page-link" href="@Url.Action("AllUsers", "UserAccount", new { searchString = ViewBag.SearchString, page = ViewBag.Page - 1 })">Previous</a>
            </li>
        }
        else
        {
            <li class="page-item disabled">
                <a class="page-link" href="@Url.Action("AllUsers", "UserAccount", new {searchString = ViewBag.SearchString, page = ViewBag.Page - 1  })">Previous</a>
            </li>
        }


        @for (int i = 1; i <= ViewBag.PageCount; i++)
        {
            <li class="page-item @(ViewBag.Page == i ? "active" : "")">
                <a class="page-link" href="@Url.Action("AllUsers", "UserAccount", new { searchString = ViewBag.SearchString , page = i})">@i</a>
            </li>
        }

        @if (ViewBag.Page != ViewBag.PageCount)
        {
            <li>
                <a class="page-link" href="@Url.Action("AllUsers", "UserAccount", new { searchString = ViewBag.SearchString, page = ViewBag.Page + 1 })">Next</a>
            </li>
        }
        else
        {
            <li class="page-item disabled">
                <a class="page-link" href="@Url.Action("AllUsers", "UserAccount", new {searchString = ViewBag.SearchString, page = ViewBag.Page + 1 })">Next</a>
            </li>
        }

    </ul>
</nav>



<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="~/js/User/Remove.js"></script>
<script src="~/js/User/MakeAdmin.js"></script>
<script src="~/js/User/MakeUser.js"></script>

OnlineStore/Views/UserAccount/EditProfile.cshtml
@model OnlineStore.BusinessLogic.Implementation.Account.Models.ProfileModel
@inject OnlineStore.Common.DTOs.CurrentUserDto CurrentUser
@{
    ViewData["Title"] = "Profile Page";
    ViewBag.CountryId = Convert.ToInt32(ViewBag.CountryId);

}
<h1>@ViewData["Title"]</h1>
<input type="hidden" id="countryIdHidden" name="countryId" value="@ViewBag.CountryId" />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditProfile" asp-controller="UserAccount">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CountryId" class="control-label">Country name</label>
                <select asp-for="CountryId" class="form-control" id="countryDropdown"></select>
                <span asp-validation-for="CountryId" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
                <a href="@Url.Action("Profile", "UserAccount", new { id = CurrentUser.Id })" class="btn btn-warning">Cancel</a>
            </div>
        </form>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="~/js/User/EditCountryList.js"></script>
<script src="~/js/User/CountryForEdit.js"></script>
<script>new CountryForEdit();</script>

OnlineStore/Views/UserAccount/Orders.cshtml
@model IEnumerable<OnlineStore.Common.DTOs.OrderDto>

<table class="table">
    <thead>
        <tr>
            <th>Order ID</th>
            <th>Total Price</th>
            <th>Details</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var order in Model)
        {
            <tr>
                <td>@order.Id</td>
                <td>@order.TotalPrice</td>
                <td>
                    <a href="@Url.Action("OrderDetails", "Order", new { Id = order.Id })" class="btn btn-primary">Details</a>
                </td>
            </tr>

        }
    </tbody>
</table>

OnlineStore/Views/UserAccount/Profile.cshtml
@model OnlineStore.BusinessLogic.Implementation.Account.Models.ProfileModel

@inject OnlineStore.Common.DTOs.CurrentUserDto CurrentUser

@{
    ViewData["Title"] = "Profile Page";
}

<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>
</head>
<body>
    <h1>@ViewData["Title"]</h1>

    <div>
        <p><strong>Username:</strong> @Model.UserName</p>
        <p><strong>Email:</strong> @Model.Email</p>
        <p><strong>First Name:</strong> @Model.FirstName</p>
        <p><strong>Last Name:</strong> @Model.LastName</p>
        <p><strong>Country:</strong> @Model.Country</p>
    </div>

    <div>
        <a href="@Url.Action("Orders", "UserAccount")" class="btn btn-secondary">Orders</a>
        <a href="@Url.Action("EditProfile", "UserAccount", new { id = CurrentUser.Id })" class="btn btn-success">Edit Profile</a>
        <a  href="@Url.Action("DeleteAccount", "UserAccount")" class="btn btn-danger"> Delete Account </a>
    </div>
</body>
</html>

OnlineStore/Views/UserAccount/Register.cshtml
@model OnlineStore.BusinessLogic.Implementation.Account.Models.RegisterModel

@{
    ViewData["Title"] = "View";
}

@*@Html.DropDownListFor(m => m.CountryList,
            new SelectList(Enum.GetValues(typeof(@Model.CountryId))),
            "Select Gender")*@
<script src="~/js/User/CountryList.js"></script>
<h1>Register</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Register" asp-controller="UserAccount">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" type="password" class="form-control"  />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmPassword" class="control-label"> Confirm Password</label>
                <input asp-for="ConfirmPassword" type="password" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CountryId" class="control-label">Country name</label>
                <select asp-for="CountryId" class="form-control" id="countryDropdown">
                </select>
                <span asp-validation-for="CountryId" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" value="Register" class="btn btn-dark" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}
<script  src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="~/js/User/CountryList.js"></script>
<script>new CountryList()</script>

OnlineStore/Views/UserAccount/ShoppingCart.cshtml
@model IEnumerable<OnlineStore.Common.DTOs.ShoppingCartDto>
@inject OnlineStore.Common.DTOs.CurrentUserDto CurrentUser

<link rel="stylesheet" href="~/css/ShoppingCart/ShoppingCart.css" />


@if (Model.Count() == 0)
{
    <div class="shopImage">
        <img src="~/Images/5249.jpg" class="shopImage" />
    </div>

}
else
{

    <table>
        <h2>Shopping Cart</h2>
        <tr>
            <th>Product Name</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Measure</th>
            <th>Subtotal</th>


        </tr>

        @foreach (var item in Model)
        {
            <tr id="item-@item.ProductId-@item.ProductSize">

                <td>
                    <img src="data:image/png;base64,@Convert.ToBase64String(item.ProductImage)" />
                    <a href="@Url.Action("ProductDetails", "Product", new { id = item.ProductId })" style="text-decoration: none ; color: black">@item.ProductName</a>
                </td>
                <td>@(item.ProductPrice - (item.ProductPrice * item.ProductDiscount / 100)) USD </td>
                <td>
                    @item.Quantity
                    <button class="decrease-quantity" onclick="DecreaseQuantity('@item.ProductId', '@item.ProductSize')">-</button>
                    <button class="increase-quantity" onclick="IncreaseQuantity('@item.ProductId', '@item.ProductSize')">+</button>
                </td>
                <td>@item.ProductSize</td>
                <td>@((item.ProductPrice - (item.ProductPrice * item.ProductDiscount / 100)) * item.Quantity) USD</td>
                <td class="remove-cell">
                    <button type="button" class="remove-button btn-secondary" onclick="RemoveItem('@item.ProductId','@item.ProductSize')">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-lg" viewBox="0 0 16 16">
                            <path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8 2.146 2.854Z"></path>
                        </svg>
                    </button>
                </td>



            </tr>

        }
    </table>

    <div class="total-price">
        <h3>Total Price: @Model.Sum(x => (x.ProductPrice - (x.ProductPrice * x.ProductDiscount / 100)) * x.Quantity)</h3>
    </div>

    <div class="checkout-button">
        <a href="@Url.Action("CheckOut", "ShoppingCart")" class="btn btn-dark"> <i class="bi bi-credit-card-2-front"> Pay Now</i></a>
    </div>
    <div id="notification" class="notification hidden"></div>
}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="~/js/ShoppingCart/RemoveItem.js"></script>
<script src="~/js/ShoppingCart/IncreaseQuantity.js"></script>
<script src="~/js/ShoppingCart/DecreaseQuantity.js"></script>